In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn

### Vector

In [2]:
temp = torch.FloatTensor([23,24,24.5,26,27.2,23.0])
temp.size()

torch.Size([6])

In [3]:
temp

tensor([23.0000, 24.0000, 24.5000, 26.0000, 27.2000, 23.0000])

### Scalar

In [4]:
x = torch.rand(10)
x.size()

torch.Size([10])

In [5]:
x

tensor([0.9943, 0.0728, 0.1959, 0.3605, 0.6960, 0.4421, 0.0355, 0.0555, 0.1823,
        0.5225])

### Matrix

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
df = pd.read_csv("/content/drive/MyDrive/Cases/Concrete Strength/Concrete_Data.csv")
df.head()

Cement  Blast  Fly  Water  Superplasticizer  Coarse   Fine  Age  Strength
0   540.0    0.0  0.0  162.0               2.5  1040.0  676.0   28     79.99
1   540.0    0.0  0.0  162.0               2.5  1055.0  676.0   28     61.89
2   332.5  142.5  0.0  228.0               0.0   932.0  594.0  270     40.27
3   332.5  142.5  0.0  228.0               0.0   932.0  594.0  365     41.05
4   198.6  132.4  0.0  192.0               0.0   978.4  825.5  360     44.30

In [8]:
df.values

array([[540.  ,   0.  ,   0.  , ..., 676.  ,  28.  ,  79.99],
       [540.  ,   0.  ,   0.  , ..., 676.  ,  28.  ,  61.89],
       [332.5 , 142.5 ,   0.  , ..., 594.  , 270.  ,  40.27],
       ...,
       [148.5 , 139.4 , 108.6 , ..., 780.  ,  28.  ,  23.7 ],
       [159.1 , 186.7 ,   0.  , ..., 788.9 ,  28.  ,  32.77],
       [260.9 , 100.5 ,  78.3 , ..., 761.5 ,  28.  ,  32.4 ]])

In [9]:
df_tensor = torch.from_numpy(df.values)
df_tensor.size()

torch.Size([1030, 9])

In [10]:
df_tensor[:2]

tensor([[ 540.0000,    0.0000,    0.0000,  162.0000,    2.5000, 1040.0000,
          676.0000,   28.0000,   79.9900],
        [ 540.0000,    0.0000,    0.0000,  162.0000,    2.5000, 1055.0000,
          676.0000,   28.0000,   61.8900]], dtype=torch.float64)